[build]
  publish = "public"
  command = "npm run build"
  functions = "functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = "functions"

  [functions.timeout]
  duration = "20s"